
/* #########################################################################
 * [2016-12-13 14:59:47.260000] THIS FILE IS AUTOGENERATED - DO NOT EDIT!
 * ######################################################################### */

#ifndef ___MULTISPEQ1___
#define ___MULTISPEQ1___

#include "Multispeq1/Properties.h"
#include "Multispeq1/CommandProcessor.h"

#endif  // #ifndef ___MULTISPEQ1___

